apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/replace-me/booking-frontend
    newTag: prod-latest
  - name: ghcr.io/replace-me/booking-backend
    newTag: prod-latest
  - name: ghcr.io/replace-me/booking-agent
    newTag: prod-latest
  - name: ghcr.io/replace-me/booking-agent-langgraph
    newTag: prod-latest
